entry point compatible with v2 aiida entry point
aiidateam/aiida-code-registry pull request #64
Opened 2022-09-05 13:31 UTC by unkcpz

2022-09-06 13:18 UTC, yakutovicha requested changes
Thanks, @unkcpz, I have a couple of suggestions.

2022-09-06 13:18 UTC, yakutovicha commented on .make_ghpages/generate_json.py
> +            final_dict_v2[domain][computer]["computer-setup"] = update_to_v2_entry_points(final_dict_v2[domain][computer]["computer-setup"])
I would rather run something like this here:
```suggestion
            update_to_v2_entry_points(final_dict_v2[domain][computer]["computer-setup"])
```
and remove `res = copy.deepcopy(comp_setup)` line in `update_to_v2_entry_points`. The dictionary is already| "deep copied", so this it is safe to modify it directly here.

2022-09-06 13:18 UTC, yakutovicha commented on .make_ghpages/generate_json.py
> +    json.dump(final_dict_v2, filep, indent=4)
```suggestion
    json.dump(final_dict_v2, filep, indent=4)

```

2022-09-06 13:18 UTC, yakutovicha commented on .make_ghpages/generate_json.py
> +    return res
```suggestion
    for key in ['transport', 'scheduler']:
        try:
            comp_setup[key] = f"core.{comp_setup[key]}"
        except KeyError:
            print(f"No {key} key specified for {comp_setup['label']}")
```

2022-09-06 14:40 UTC, unkcpz commented
@yakutovicha thanks! changed.

2022-09-06 14:43 UTC, yakutovicha approved these changes
All good, thanks!

2022-09-06 14:44 UTC, merged

2022-09-07 11:14 UTC, yakutovicha commented
> One way is to set these parameters for all config yaml files and let 1.x ignore them.

sure can you make a PR for this?