Renew the deploy flow
aiidateam/aiida-code-registry pull request #65
Opened 2022-09-06 15:20 UTC by unkcpz

2022-09-15 09:25 UTC, yakutovicha requested changes
Thanks, @unkcpz. Just a couple of minor changes.

2022-09-15 09:25 UTC, yakutovicha commented on .github/workflows/deploy.yml
> +    if: github.repository == 'aiidateam/aiida-code-registry' # xxx: change to aiidateam after
```suggestion
    if: github.repository == 'aiidateam/aiida-code-registry'
```

2022-09-15 09:25 UTC, yakutovicha commented on .make_ghpages/index.html
> +</html>
```suggestion
</html>

```

2022-09-15 09:25 UTC, yakutovicha commented on .make_ghpages/index.html
> +<h1>Code registry</h1>
```suggestion
<h1>AiiDA codes and computers registry</h1>
```

2022-09-16 06:24 UTC, unkcpz commented
@yakutovicha thanks! changed.

2022-09-19 09:40 UTC, yakutovicha approved these changes

2022-09-19 09:41 UTC, merged