Support v2.1 InstalledCode setup
aiidateam/aiida-code-registry pull request #77
Opened 2022-12-04 14:24 UTC by unkcpz

2022-12-06 09:00 UTC, unkcpz commented
This one should be tested with awb before merge.

2022-12-06 16:12 UTC, yakutovicha requested changes
Thanks, @unkcpz, just one small request.

2022-12-08 10:05 UTC, yakutovicha commented on .github/workflows/deploy.yml
> +        if: github.repository == 'unkcpz/aiida-code-registry'
So you are not planning to merge it? If so, I guess it. makes sense to convert the PR to a draft.

2022-12-08 10:43 UTC, unkcpz commented on .github/workflows/deploy.yml
> +        if: github.repository == 'unkcpz/aiida-code-registry'
Yep, changed.

2022-12-08 13:45 UTC, yakutovicha approved these changes

2022-12-08 13:50 UTC, merged